######################################################################
# Automatically generated by qmake (2.01a) Fri May 7 11:19:23 2010
######################################################################

TEMPLATE = app
TARGET = greebo
DEPENDPATH += .
INCLUDEPATH += .

CONFIG -= app_bundle

OBJECTS_DIR = obj
MOC_DIR = obj

# Input
SOURCES += \
    main.cpp \
    MainWindow.cpp \

HEADERS += \
    MainWindow.h \

